### ISSUE TITLE
Content is too wide

### ISSUE THREAD

**Issue by smileBeda** [aspirepress/site-theme#20]
Content inside `article` is full width and tires to read.
use something like `max-width: 666px; margin: auto;` on the `article` tag.

**Comment by verlev** [comment]
Since it's a temporary site, would suggest to do this as simple as possible without having too many layout shifts.

a) restrict ALL page content to 75ch (titles will be longer, is OK)
b) allow for wide-width elements (for now: media-text & posts list on the home page, they would become too small; so for now the home page _would_ appear wider)

(maybe all form fields should become fullwidth iso medium, though that's an admin setting I suppose)

Think this should suffice:

```
/* Restraining content width */
.blog-main {
    width: 100%;
    max-width: calc( 75ch + 10vw + 10vw);
    margin-left: auto;
    margin-right: auto;
    float: none;
    overflow: hidden;
}

/* Add all wide width items */
.alignwide,
.wp-block-media-text,
.wp-block-latest-posts__list {
	max-width: calc( 100% + 8vw + 8vw );
	margin-left: -8vw;
	margin-right: -8vw;
}
/* Align titles with their wide width blocks */
h2:has(+ .wp-block-latest-posts__list) {
	border: red 1px solid;
	max-width: calc( 100% + 8vw + 8vw );
	margin-left: -8vw;
	margin-right: -8vw;
}
```



+ small fix for the faulty left-indenting media-text content (home)
```
.wp-block-media-text.has-media-on-the-right:not(.has-background) > .wp-block-media-text__content {
	padding-left: 0;
}
```

+ small fix for jumping news header (no .page-header class) — update on r373, add ".blog h1"
```
.page-header,
.blog h1 {
    padding-bottom: 9px;
    margin: 40px 0 40px;
    border-bottom: none;
}
```

**Comment by kylek14** [comment]
Reviewed @verlev's suggested fix and they're good to incorporate into Main. Will patch this evening and close issue once merged.
