### ISSUE TITLE
comments - reply is over the date on mobile

### ISSUE THREAD

**Issue by ipajen** [aspirepress/site-theme#21]
On iPhone SE, 18.0.1, safari 
On comments the reply is over the date
For example on

https://aspirepress.org/publishing-and-distributing-first-party-packages-for-wordpress/

see picture:
![IMG_8468](https://github.com/user-attachments/assets/982fdb64-e25f-43ac-8a45-3c01be998931)

**Comment by verlev** [comment]
For now, you could add a quick fix: whenever they may start to 'bump', up the padding, add a margin to the comment-body & make the meta sit 'in' the padding. Still did align really weird (due to fixed float), so added the comment-body width width to the meta too. (1.1 line height so the overflowing nested meta still stays kind of within the padding/margin)

(tested via devtools, this should suffice)

```
@media screen and (max-width: 450px) {
	.comment-body {
        	padding-bottom: 2.5rem;
        	margin-bottom: 30px;
	}
	.comment-list .comment-metadata {
		bottom: 0;
		text-align: left;
		width: calc( 100% - 90px );
		line-height: 1.1;
	}
}
```
